services:
  postgres:
    image: 'postgres:17.6'
    environment:
      - 'POSTGRES_DB=jitterticket'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
