package dev.ted.jitterticket;

import dev.ted.jitterticket.eventsourced.adapter.out.store.CsvReaderAppender;
import dev.ted.jitterticket.eventsourced.adapter.out.store.CsvStringsEventStore;
import dev.ted.jitterticket.eventsourced.adapter.out.store.jdbc.EventDboRepository;
import dev.ted.jitterticket.eventsourced.adapter.out.store.jdbc.JdbcEventStore;
import dev.ted.jitterticket.eventsourced.application.port.EventStore;
import dev.ted.jitterticket.eventsourced.domain.concert.Concert;
import dev.ted.jitterticket.eventsourced.domain.concert.ConcertEvent;
import dev.ted.jitterticket.eventsourced.domain.concert.ConcertId;
import dev.ted.jitterticket.eventsourced.domain.customer.Customer;
import dev.ted.jitterticket.eventsourced.domain.customer.CustomerEvent;
import dev.ted.jitterticket.eventsourced.domain.customer.CustomerId;
import org.apache.logging.log4j.util.Strings;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.io.File;
import java.io.IOException;
import java.nio.file.Path;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.temporal.ChronoUnit;
import java.util.UUID;

@Configuration
public class EventStoreConfiguration {

    private static LocalDateTime daysFromNowAt(long days, int hour, int minute) {
        return LocalDateTime.now()
                .truncatedTo(ChronoUnit.DAYS)
                .plusDays(days)
                .withHour(hour)
                .withMinute(minute);
    }

    static final ConcertId SONIC_WAVES_CONCERT_ID = new ConcertId(UUID.fromString("123e4567-e89b-42d3-a456-556642440001"));


    @Bean
    public EventStore<CustomerId, CustomerEvent, Customer> customerStore(@Value("${events.directory}") String eventsDirectory, EventDboRepository eventDboRepository) throws IOException {
//        var customerStore = InMemoryEventStore.forCustomers();
//        var customerStore = csvCustomerEventStoreIn(eventsDirectory);

        return JdbcEventStore.forCustomers(eventDboRepository);
    }

    private EventStore<CustomerId, CustomerEvent, Customer> csvCustomerEventStoreIn(String eventsDirectory) throws IOException {
        String eventsFilePath = eventsDirectory + File.separator + "customer-events.csv";
        return CsvStringsEventStore.forCustomers(new CsvReaderAppender(Path.of(eventsFilePath)));
    }

    @Bean
    public EventStore<ConcertId, ConcertEvent, Concert> concertStore(@Value("${events.directory}") String eventsDirectory, EventDboRepository eventDboRepository) throws IOException {
        if (Strings.isBlank(eventsDirectory)) {
            throw new IllegalArgumentException("eventsDirectory (from events.directory) is empty");
        }
//        var concertStore = InMemoryEventStore.forConcerts();
//        var concertStore = csvConcertStoreIn(eventsDirectory);
        var concertStore = JdbcEventStore.forConcerts(eventDboRepository);

        // don't add sample data if the file already exists
        if (!concertStore.allEvents().toList().isEmpty()) {
            return concertStore;
        }

        addSonicWavesConcertTo(concertStore);

        // rest of data generated by my good friend Junie
        concertStore.save(Concert.schedule(
                ConcertId.createRandom(),
                "Midnight Rebels",
                55,
                daysFromNowAt(15, 21, 0),
                LocalTime.of(20, 0),
                150,
                4));

// Example 2: Jazz ensemble with limited capacity
        concertStore.save(Concert.schedule(
                ConcertId.createRandom(),
                "Blue Note Quartet",
                35,
                daysFromNowAt(83, 19, 30),
                LocalTime.of(18, 30),
                75,
                2));

// Example 3: Popular pop artist with higher capacity
        concertStore.save(Concert.schedule(
                ConcertId.createRandom(),
                "Stella Nova",
                65,
                daysFromNowAt(5, 20, 0),
                LocalTime.of(18, 30),
                250,
                6));

// Example 4: Indie folk band with afternoon show
        concertStore.save(Concert.schedule(
                ConcertId.createRandom(),
                "Woodland Echoes",
                30,
                daysFromNowAt(73, 16, 0),
                LocalTime.of(15, 0),
                120,
                4));

// Example 5: Electronic music DJ with a late night show
        concertStore.save(Concert.schedule(
                ConcertId.createRandom(),
                "Pulse Wave",
                40,
                daysFromNowAt(39, 22, 30),
                LocalTime.of(21, 0),
                180,
                5));

// Example 6: Classical orchestra
        concertStore.save(Concert.schedule(
                ConcertId.createRandom(),
                "Metropolitan Symphony",
                70,
                daysFromNowAt(81, 19, 0),
                LocalTime.of(18, 0),
                200,
                3));

// Example 7: Alternative rock band
        concertStore.save(Concert.schedule(
                ConcertId.createRandom(),
                "Cosmic Drift",
                45,
                daysFromNowAt(109, 20, 0),
                LocalTime.of(19, 0),
                130,
                4));

// Example 8: Hip-hop artist
        concertStore.save(Concert.schedule(
                ConcertId.createRandom(),
                "Lyrical Storm",
                50,
                daysFromNowAt(31, 21, 0),
                LocalTime.of(19, 30),
                175,
                4));

        // h/t sadukie
        concertStore.save(Concert.schedule(
                ConcertId.createRandom(),
                "Jagged Arrays",
                50,
                daysFromNowAt(34, 20, 0),
                LocalTime.of(19, 0),
                150,
                6));
        return concertStore;
    }

    private static EventStore<ConcertId, ConcertEvent, Concert> csvConcertStoreIn(String eventsDirectory) throws IOException {
        String eventsFilePath = eventsDirectory + File.separator + "concert-events.csv";
        var concertStore = CsvStringsEventStore.forConcerts(
                new CsvReaderAppender(Path.of(eventsFilePath)));
        return concertStore;
    }

    private static void addSonicWavesConcertTo(EventStore<ConcertId, ConcertEvent, Concert> concertStore) {
        Concert sonicWavesConcert = Concert.schedule(
                SONIC_WAVES_CONCERT_ID,
                "The Sonic Waves",
                45,
                daysFromNowAt(26, 20, 0),
                LocalTime.of(19, 0),
                100,
                8);

        sonicWavesConcert.rescheduleTo(
                daysFromNowAt(33, 21, 0),
                LocalTime.of(20, 0));

        sonicWavesConcert.sellTicketsTo(CustomerId.createRandom(), 8);
        sonicWavesConcert.sellTicketsTo(CustomerId.createRandom(), 4);
        sonicWavesConcert.sellTicketsTo(CustomerId.createRandom(), 2);
        sonicWavesConcert.sellTicketsTo(CustomerId.createRandom(), 1);
        sonicWavesConcert.sellTicketsTo(CustomerId.createRandom(), 2);
        sonicWavesConcert.sellTicketsTo(CustomerId.createRandom(), 3);

        concertStore.save(sonicWavesConcert);
    }


}
